linux-image, linux-headers: Use linux-run-hooks instead of run-parts
Use the new linux-run-hooks command from linux-base instead of
directly calling run-parts.  This adds support for hooks under
/usr/share/kernel, assuming a sufficiently recent debianutils.

linux-image: Bump the versioned dependency on linux-base.  Move it to
Pre-Depends since we will now also call it from the preinst script.

linux-headers: Add a versioned dependency on linux-base.

Closes: #1101733

diff --git a/debian/templates/image.postrm.in b/debian/templates/image.postrm.in
--- a/debian/templates/image.postrm.in
+++ b/debian/templates/image.postrm.in
@@ -9,9 +9,10 @@ if [ "$1" != upgrade ] && command -v linux-update-symlinks >/dev/null; then
     linux-update-symlinks remove $version $image_path
 fi
 
-if [ -d /etc/kernel/postrm.d ]; then
-    DEB_MAINT_PARAMS="$*" run-parts --report --exit-on-error --arg=$version \
-	      --arg=$image_path /etc/kernel/postrm.d
+if command -v linux-run-hooks >/dev/null; then
+    linux-run-hooks image postrm $version $image_path -- "$@"
+else
+    echo >&2 'W: linux-base is not installed; cannot run postrm hooks'
 fi
 
 if [ "$1" = purge ]; then
